name: LinuxCommandTest

on:
  workflow_dispatch:
   
jobs:
  TestCommands:

    runs-on: ubuntu-latest

    steps:
    - name: Test commands
      run: |
         echo Check CPU utilization
         mpstat 1 1  

         echo Check memory utilization
         free 
        
         echo Check filesystem utilization
         df --output=pcent / | tail -1 

         echo "CPU Utilization: $(mpstat 1 1 | awk '/Average/ {print 100 - $12}')%"
         echo "Memory Utilization: $(free | awk '/Mem/ {print $3/$2 * 100.0}')%"
         echo "Filesystem Utilization: $(df --output=pcent / | tail -1 | tr -d '%')%"

         
