name: Parent workflow

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          pwd
          ls -lrta
          curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ secrets.CPQ_CROSS_REPO_PAT }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/2115-27/react-login-page/actions/runs/$GITHUB_RUN_ID/jobs
         
        env:
            GH_TOKEN: ${{ secrets.REPO_SCOPE_SECRET }}
            
      - run: echo "Hello world"
